In [2]:
!pip install Numpy

In [3]:
import numpy as np

In [4]:
list=[1,2,3,4]

In [5]:
type(list)

list

In [6]:
arr=np.array(list)

In [7]:
arr

array([1, 2, 3, 4])

In [8]:
type(arr)

numpy.ndarray

In [9]:
1
2
3
4

4

In [10]:
arr.size

4

In [11]:
1
2
3

3

In [12]:
arr.size

4

In [13]:
z=np.zeros(10)

In [14]:
z.size

10

In [15]:
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
z=np.ones(3)

In [17]:
z

array([1., 1., 1.])

In [18]:
o=np.array([1,2,3,4])

In [19]:
o

array([1, 2, 3, 4])

In [20]:
o.ndim
#dimensions

1

In [21]:
o.shape

(4,)

In [22]:
x=np.array([[1,2,3],[4,5,6],[7,8,9],[3,2,1]])

In [23]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [3, 2, 1]])

In [24]:
x.ndim

2

In [25]:
x.shape

(4, 3)

In [26]:
x=x.reshape(3,2,2)
x

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[9, 3],
        [2, 1]]])

In [27]:
x.ndim

3

In [28]:
x.reshape(3,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 3, 2, 1]])

In [29]:
x

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[9, 3],
        [2, 1]]])

In [30]:
x=x.reshape(3,4)

In [31]:
x.ndim

2

In [32]:
x.shape

(3, 4)

# Indexing

In [33]:
arr=np.array([1,2,3,4])

In [34]:
arr[1]

2

In [35]:
arr[1]+arr[2]

5

In [36]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [37]:
print("2nd element in first dimension",arr[0,1])

2nd element in first dimension 2


In [38]:
#linspace
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [39]:
#Identity
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
#random
np.random.randint(0,10,10)

array([3, 4, 5, 2, 6, 6, 3, 0, 7, 1])

In [41]:
np.random.rand(3,3)

array([[0.48984161, 0.24397482, 0.01969965],
       [0.38105157, 0.62868733, 0.24481114],
       [0.75982346, 0.41103344, 0.9939748 ]])

In [42]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [43]:
arr.max()

10

In [44]:
arr.argmax()

9

In [45]:
x.argmin()

0

In [46]:
x.min()

1

In [49]:
a=np.arange(0,11,2)

In [50]:
a

array([ 0,  2,  4,  6,  8, 10])

# Slicing

In [51]:
a[1:3]

array([2, 4])

In [52]:
a=np.array([[1,2,3],[2,3,4],[4,5,6]])

In [53]:
a

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [54]:
a[0:1,0:2]

array([[1, 2]])

In [56]:
 a[0:2,1:3]

array([[2, 3],
       [3, 4]])

In [57]:
 a[2:,0:2]

array([[4, 5]])

In [58]:
a=np.arange(0,11,2)

In [59]:
a

array([ 0,  2,  4,  6,  8, 10])

In [60]:
a1=np.arange(0,11,2)

In [61]:
c=a+a1

In [62]:
c

array([ 0,  4,  8, 12, 16, 20])

In [63]:
np.sqrt(c)

array([0.        , 2.        , 2.82842712, 3.46410162, 4.        ,
       4.47213595])

In [64]:
np.sin(c)

array([ 0.        , -0.7568025 ,  0.98935825, -0.53657292, -0.28790332,
        0.91294525])

In [68]:
arr=np.array([1,2,3,4,5])
x=arr.copy()

In [69]:
x

array([1, 2, 3, 4, 5])

In [70]:
z=arr.view()

In [71]:
z

array([1, 2, 3, 4, 5])

In [72]:
arr[1]=45

In [73]:
arr

array([ 1, 45,  3,  4,  5])

In [74]:
z

array([ 1, 45,  3,  4,  5])

In [75]:
x

array([1, 2, 3, 4, 5])